---
name: Rocky9

on:
  push:
    branches: [ master ]
    paths-ignores:
      - '*.md'

  pull_request:
    branches: [ master ]

jobs:
  Rocky9:

    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:9

    steps:
    - uses: actions/checkout@v3
    - name: Install required packages
      run: |
        dnf -y install dnf-plugins-core
        dnf update -y
        dnf -y install "epel-release"
        dnf update -y
        dnf install -y git make sudo tree which automake gcc gcc-c++ glibc-devel libtool flex binutils strace
    - name: Configuration
      run: |
        make init
        make vars
        make conf
        make conf.systemd
        make conf.systemd.show
        make conf.properties
        make conf.properties.show
    - name: Build 
      run: |
        make src_install
        make conf_install
    - name: Environment Check
      run: make exist

